#!/bin/sh

set -e

case "$1" in
    configure)
	# (cd /var/lib/dash && PYTHONPATH=/var/lib/dash python dashboard/manage.py syncdb) > /dev/null 2>&1

	# # set permissions
	# for i in $(find /var/lib/dash/local -type f); do
	#     if ! dpkg-statoverride --list ${1} > /dev/null 2>&1; then
	# 	dpkg-statoverride --update --add www-data www-data 640 ${i}
	#     fi
	# done
	;;

    abort-upgrade|abort-remove|abort-deconfigure)
	;;

    *)
	echo "postinst called with unknown argument \`$1'" >&2
	exit 0
	;;
esac

#DEBHELPER#

